name: EonaSpawnerListe
version: 0.3
author: Bloodrayne1995
website: http://eona-minecraft.de
main: eonaminecraft.MainPlugin
depend: [Vault]
api-version: 1.13
commands:
  sl:
    description: Zugriff auf die Spawnerliste
  spawnerliste:
    description: Zugriff auf die Spawnerliste

