name: EonaSpawnerListe
version: 0.1
author: Bloodrayne1995
website: http://eona-minecraft.de
main: eonaminecraft.MainPlugin
depend: [Vault]
commands:
  sl:
    description: Zugriff auf die Spawnerliste
  spawnerliste:
    description: Zugriff auf die Spawnerliste

